name: example
description: An example application that demonstrates how to use a the draggable_scrollbar package 

dependencies:
  draggable_scrollbar:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
